/* Generated by Yosys 0.51+85 (git sha1 d3aec12fe, clang++ 18.1.8 -fPIC -O3) */

(* top =  1  *)
(* src = "gcd.v:11.1-102.10" *)
module gcd(clk, req_msg, req_rdy, req_val, reset, resp_msg, resp_rdy, resp_val);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  (* src = "gcd.v:13.15-13.18" *)
  input clk;
  wire clk;
  (* src = "gcd.v:32.19-32.33" *)
  wire \ctrl$b_mux_sel ;
  (* src = "gcd.v:26.19-26.27" *)
  wire \ctrl$clk ;
  (* src = "gcd.v:35.19-35.31" *)
  wire \ctrl$req_rdy ;
  (* src = "gcd.v:28.19-28.31" *)
  wire \ctrl$req_val ;
  (* src = "gcd.v:29.19-29.29" *)
  wire \ctrl$reset ;
  (* src = "gcd.v:25.19-25.32" *)
  wire \ctrl$resp_rdy ;
  (* src = "gcd.v:31.19-31.32" *)
  wire \ctrl$resp_val ;
  (* hdlname = "ctrl b_mux_sel" *)
  (* src = "gcd.v:113.24-113.33" *)
  wire \ctrl.b_mux_sel ;
  (* hdlname = "ctrl clk" *)
  (* src = "gcd.v:115.24-115.27" *)
  wire \ctrl.clk ;
  (* hdlname = "ctrl req_rdy" *)
  (* src = "gcd.v:118.24-118.31" *)
  wire \ctrl.req_rdy ;
  (* hdlname = "ctrl req_val" *)
  (* src = "gcd.v:119.24-119.31" *)
  wire \ctrl.req_val ;
  (* hdlname = "ctrl reset" *)
  (* src = "gcd.v:120.24-120.29" *)
  wire \ctrl.reset ;
  (* hdlname = "ctrl resp_rdy" *)
  (* src = "gcd.v:121.24-121.32" *)
  wire \ctrl.resp_rdy ;
  (* hdlname = "ctrl resp_val" *)
  (* src = "gcd.v:122.24-122.32" *)
  wire \ctrl.resp_val ;
  (* hdlname = "ctrl state$clk" *)
  (* src = "gcd.v:147.19-147.28" *)
  wire \ctrl.state$clk ;
  (* hdlname = "ctrl state$reset" *)
  (* src = "gcd.v:146.19-146.30" *)
  wire \ctrl.state$reset ;
  (* hdlname = "ctrl state clk" *)
  (* src = "gcd.v:331.24-331.27" *)
  wire \ctrl.state.clk ;
  (* onehot = 32'd1 *)
  wire [2:0] \ctrl.state.out ;
  (* hdlname = "ctrl state reset" *)
  (* src = "gcd.v:334.24-334.29" *)
  wire \ctrl.state.reset ;
  (* src = "gcd.v:58.19-58.34" *)
  wire \dpath$b_mux_sel ;
  (* src = "gcd.v:55.19-55.28" *)
  wire \dpath$clk ;
  (* src = "gcd.v:57.19-57.34" *)
  wire [15:0] \dpath$req_msg_a ;
  (* src = "gcd.v:56.19-56.34" *)
  wire [15:0] \dpath$req_msg_b ;
  (* src = "gcd.v:59.19-59.30" *)
  wire \dpath$reset ;
  (* src = "gcd.v:63.19-63.33" *)
  wire [15:0] \dpath$resp_msg ;
  (* hdlname = "dpath a_lt_b$clk" *)
  (* src = "gcd.v:406.19-406.29" *)
  wire \dpath.a_lt_b$clk ;
  (* hdlname = "dpath a_lt_b$in0" *)
  (* src = "gcd.v:407.19-407.29" *)
  wire [15:0] \dpath.a_lt_b$in0 ;
  (* hdlname = "dpath a_lt_b$in1" *)
  (* src = "gcd.v:408.19-408.29" *)
  wire [15:0] \dpath.a_lt_b$in1 ;
  (* hdlname = "dpath a_lt_b$reset" *)
  (* src = "gcd.v:405.19-405.31" *)
  wire \dpath.a_lt_b$reset ;
  (* hdlname = "dpath a_lt_b clk" *)
  (* src = "gcd.v:589.24-589.27" *)
  wire \dpath.a_lt_b.clk ;
  (* hdlname = "dpath a_lt_b in0" *)
  (* src = "gcd.v:590.24-590.27" *)
  wire [15:0] \dpath.a_lt_b.in0 ;
  (* hdlname = "dpath a_lt_b in1" *)
  (* src = "gcd.v:591.24-591.27" *)
  wire [15:0] \dpath.a_lt_b.in1 ;
  (* hdlname = "dpath a_lt_b reset" *)
  (* src = "gcd.v:593.24-593.29" *)
  wire \dpath.a_lt_b.reset ;
  (* hdlname = "dpath a_mux$clk" *)
  (* src = "gcd.v:439.19-439.28" *)
  wire \dpath.a_mux$clk ;
  (* hdlname = "dpath a_mux$in_$000" *)
  (* src = "gcd.v:436.19-436.32" *)
  wire [15:0] \dpath.a_mux$in_$000 ;
  (* hdlname = "dpath a_mux$in_$001" *)
  (* src = "gcd.v:437.19-437.32" *)
  wire [15:0] \dpath.a_mux$in_$001 ;
  (* hdlname = "dpath a_mux$in_$002" *)
  (* src = "gcd.v:438.19-438.32" *)
  wire [15:0] \dpath.a_mux$in_$002 ;
  (* hdlname = "dpath a_mux$reset" *)
  (* src = "gcd.v:435.19-435.30" *)
  wire \dpath.a_mux$reset ;
  (* hdlname = "dpath a_mux clk" *)
  (* src = "gcd.v:651.24-651.27" *)
  wire \dpath.a_mux.clk ;
  (* hdlname = "dpath a_mux in_$000" *)
  (* src = "gcd.v:652.24-652.31" *)
  wire [15:0] \dpath.a_mux.in_$000 ;
  (* hdlname = "dpath a_mux in_$001" *)
  (* src = "gcd.v:653.24-653.31" *)
  wire [15:0] \dpath.a_mux.in_$001 ;
  (* hdlname = "dpath a_mux in_$002" *)
  (* src = "gcd.v:654.24-654.31" *)
  wire [15:0] \dpath.a_mux.in_$002 ;
  (* hdlname = "dpath a_mux in_[0]" *)
  (* src = "gcd.v:665.19-665.22" *)
  wire [15:0] \dpath.a_mux.in_[0] ;
  (* hdlname = "dpath a_mux in_[1]" *)
  (* src = "gcd.v:665.19-665.22" *)
  wire [15:0] \dpath.a_mux.in_[1] ;
  (* hdlname = "dpath a_mux in_[2]" *)
  (* src = "gcd.v:665.19-665.22" *)
  wire [15:0] \dpath.a_mux.in_[2] ;
  (* hdlname = "dpath a_mux reset" *)
  (* src = "gcd.v:656.24-656.29" *)
  wire \dpath.a_mux.reset ;
  (* hdlname = "dpath a_reg$clk" *)
  (* src = "gcd.v:391.19-391.28" *)
  wire \dpath.a_reg$clk ;
  (* hdlname = "dpath a_reg$out" *)
  (* src = "gcd.v:393.19-393.28" *)
  wire [15:0] \dpath.a_reg$out ;
  (* hdlname = "dpath a_reg$reset" *)
  (* src = "gcd.v:389.19-389.30" *)
  wire \dpath.a_reg$reset ;
  (* hdlname = "dpath a_reg clk" *)
  (* src = "gcd.v:553.24-553.27" *)
  wire \dpath.a_reg.clk ;
  (* hdlname = "dpath a_reg out" *)
  (* src = "gcd.v:556.24-556.27" *)
  wire [15:0] \dpath.a_reg.out ;
  (* hdlname = "dpath a_reg reset" *)
  (* src = "gcd.v:557.24-557.29" *)
  wire \dpath.a_reg.reset ;
  (* hdlname = "dpath b_mux$clk" *)
  (* src = "gcd.v:458.19-458.28" *)
  wire \dpath.b_mux$clk ;
  (* hdlname = "dpath b_mux$in_$000" *)
  (* src = "gcd.v:456.19-456.32" *)
  wire [15:0] \dpath.b_mux$in_$000 ;
  (* hdlname = "dpath b_mux$in_$001" *)
  (* src = "gcd.v:457.19-457.32" *)
  wire [15:0] \dpath.b_mux$in_$001 ;
  (* hdlname = "dpath b_mux$reset" *)
  (* src = "gcd.v:455.19-455.30" *)
  wire \dpath.b_mux$reset ;
  (* hdlname = "dpath b_mux$sel" *)
  (* src = "gcd.v:459.19-459.28" *)
  wire \dpath.b_mux$sel ;
  (* hdlname = "dpath b_mux clk" *)
  (* src = "gcd.v:694.24-694.27" *)
  wire \dpath.b_mux.clk ;
  (* hdlname = "dpath b_mux in_$000" *)
  (* src = "gcd.v:695.24-695.31" *)
  wire [15:0] \dpath.b_mux.in_$000 ;
  (* hdlname = "dpath b_mux in_$001" *)
  (* src = "gcd.v:696.24-696.31" *)
  wire [15:0] \dpath.b_mux.in_$001 ;
  (* hdlname = "dpath b_mux in_[0]" *)
  (* src = "gcd.v:707.19-707.22" *)
  wire [15:0] \dpath.b_mux.in_[0] ;
  (* hdlname = "dpath b_mux in_[1]" *)
  (* src = "gcd.v:707.19-707.22" *)
  wire [15:0] \dpath.b_mux.in_[1] ;
  (* hdlname = "dpath b_mux reset" *)
  (* src = "gcd.v:698.24-698.29" *)
  wire \dpath.b_mux.reset ;
  (* hdlname = "dpath b_mux sel" *)
  (* src = "gcd.v:699.24-699.27" *)
  wire \dpath.b_mux.sel ;
  (* hdlname = "dpath b_mux_sel" *)
  (* src = "gcd.v:372.24-372.33" *)
  wire \dpath.b_mux_sel ;
  (* hdlname = "dpath b_reg$clk" *)
  (* src = "gcd.v:491.19-491.28" *)
  wire \dpath.b_reg$clk ;
  (* hdlname = "dpath b_reg$out" *)
  (* src = "gcd.v:493.19-493.28" *)
  wire [15:0] \dpath.b_reg$out ;
  (* hdlname = "dpath b_reg$reset" *)
  (* src = "gcd.v:489.19-489.30" *)
  wire \dpath.b_reg$reset ;
  (* hdlname = "dpath b_reg clk" *)
  (* src = "gcd.v:553.24-553.27" *)
  wire \dpath.b_reg.clk ;
  (* hdlname = "dpath b_reg out" *)
  (* src = "gcd.v:556.24-556.27" *)
  wire [15:0] \dpath.b_reg.out ;
  (* hdlname = "dpath b_reg reset" *)
  (* src = "gcd.v:557.24-557.29" *)
  wire \dpath.b_reg.reset ;
  (* hdlname = "dpath b_reg_out" *)
  (* src = "gcd.v:385.19-385.28" *)
  wire [15:0] \dpath.b_reg_out ;
  (* hdlname = "dpath b_zero$clk" *)
  (* src = "gcd.v:423.19-423.29" *)
  wire \dpath.b_zero$clk ;
  (* hdlname = "dpath b_zero$in_" *)
  (* src = "gcd.v:422.19-422.29" *)
  wire [15:0] \dpath.b_zero$in_ ;
  (* hdlname = "dpath b_zero$reset" *)
  (* src = "gcd.v:421.19-421.31" *)
  wire \dpath.b_zero$reset ;
  (* hdlname = "dpath b_zero clk" *)
  (* src = "gcd.v:620.24-620.27" *)
  wire \dpath.b_zero.clk ;
  (* hdlname = "dpath b_zero in_" *)
  (* src = "gcd.v:621.24-621.27" *)
  wire [15:0] \dpath.b_zero.in_ ;
  (* hdlname = "dpath b_zero reset" *)
  (* src = "gcd.v:623.24-623.29" *)
  wire \dpath.b_zero.reset ;
  (* hdlname = "dpath clk" *)
  (* src = "gcd.v:374.24-374.27" *)
  wire \dpath.clk ;
  (* hdlname = "dpath req_msg_a" *)
  (* src = "gcd.v:377.24-377.33" *)
  wire [15:0] \dpath.req_msg_a ;
  (* hdlname = "dpath req_msg_b" *)
  (* src = "gcd.v:378.24-378.33" *)
  wire [15:0] \dpath.req_msg_b ;
  (* hdlname = "dpath reset" *)
  (* src = "gcd.v:379.24-379.29" *)
  wire \dpath.reset ;
  (* hdlname = "dpath resp_msg" *)
  (* src = "gcd.v:380.24-380.32" *)
  wire [15:0] \dpath.resp_msg ;
  (* hdlname = "dpath sub$clk" *)
  (* src = "gcd.v:474.19-474.26" *)
  wire \dpath.sub$clk ;
  (* hdlname = "dpath sub$in0" *)
  (* src = "gcd.v:475.19-475.26" *)
  wire [15:0] \dpath.sub$in0 ;
  (* hdlname = "dpath sub$in1" *)
  (* src = "gcd.v:476.19-476.26" *)
  wire [15:0] \dpath.sub$in1 ;
  (* hdlname = "dpath sub$out" *)
  (* src = "gcd.v:477.19-477.26" *)
  wire [15:0] \dpath.sub$out ;
  (* hdlname = "dpath sub$reset" *)
  (* src = "gcd.v:473.19-473.28" *)
  wire \dpath.sub$reset ;
  (* hdlname = "dpath sub clk" *)
  (* src = "gcd.v:734.24-734.27" *)
  wire \dpath.sub.clk ;
  (* hdlname = "dpath sub in0" *)
  (* src = "gcd.v:735.24-735.27" *)
  wire [15:0] \dpath.sub.in0 ;
  (* hdlname = "dpath sub in1" *)
  (* src = "gcd.v:736.24-736.27" *)
  wire [15:0] \dpath.sub.in1 ;
  (* hdlname = "dpath sub out" *)
  (* src = "gcd.v:737.24-737.27" *)
  wire [15:0] \dpath.sub.out ;
  (* hdlname = "dpath sub reset" *)
  (* src = "gcd.v:738.24-738.29" *)
  wire \dpath.sub.reset ;
  (* hdlname = "dpath sub_out" *)
  (* src = "gcd.v:384.19-384.26" *)
  wire [15:0] \dpath.sub_out ;
  (* src = "gcd.v:14.24-14.31" *)
  input [31:0] req_msg;
  wire [31:0] req_msg;
  (* src = "gcd.v:15.15-15.22" *)
  output req_rdy;
  wire req_rdy;
  (* src = "gcd.v:16.15-16.22" *)
  input req_val;
  wire req_val;
  (* src = "gcd.v:17.15-17.20" *)
  input reset;
  wire reset;
  (* src = "gcd.v:18.24-18.32" *)
  output [15:0] resp_msg;
  wire [15:0] resp_msg;
  (* src = "gcd.v:19.15-19.23" *)
  input resp_rdy;
  wire resp_rdy;
  (* src = "gcd.v:20.15-20.23" *)
  output resp_val;
  wire resp_val;
  sg13g2_inv_1 _225_ (
    .A(\ctrl.state.out [0]),
    .Y(_036_)
  );
  sg13g2_inv_1 _226_ (
    .A(\dpath.a_reg.out [15]),
    .Y(_037_)
  );
  sg13g2_inv_1 _227_ (
    .A(\dpath.b_reg.out [7]),
    .Y(_038_)
  );
  sg13g2_inv_1 _228_ (
    .A(req_msg[16]),
    .Y(_039_)
  );
  sg13g2_inv_1 _229_ (
    .A(req_msg[17]),
    .Y(_040_)
  );
  sg13g2_inv_1 _230_ (
    .A(req_msg[18]),
    .Y(_041_)
  );
  sg13g2_inv_1 _231_ (
    .A(req_msg[19]),
    .Y(_042_)
  );
  sg13g2_inv_1 _232_ (
    .A(req_msg[20]),
    .Y(_043_)
  );
  sg13g2_inv_1 _233_ (
    .A(req_msg[21]),
    .Y(_044_)
  );
  sg13g2_inv_1 _234_ (
    .A(req_msg[22]),
    .Y(_045_)
  );
  sg13g2_inv_1 _235_ (
    .A(req_msg[23]),
    .Y(_046_)
  );
  sg13g2_inv_1 _236_ (
    .A(req_msg[24]),
    .Y(_047_)
  );
  sg13g2_inv_1 _237_ (
    .A(req_msg[25]),
    .Y(_048_)
  );
  sg13g2_inv_1 _238_ (
    .A(req_msg[26]),
    .Y(_049_)
  );
  sg13g2_inv_1 _239_ (
    .A(req_msg[27]),
    .Y(_050_)
  );
  sg13g2_inv_1 _240_ (
    .A(req_msg[28]),
    .Y(_051_)
  );
  sg13g2_inv_1 _241_ (
    .A(req_msg[29]),
    .Y(_052_)
  );
  sg13g2_inv_1 _242_ (
    .A(req_msg[30]),
    .Y(_053_)
  );
  sg13g2_nor2b_1 _243_ (
    .A(\dpath.a_reg.out [0]),
    .B_N(\dpath.b_reg.out [0]),
    .Y(_054_)
  );
  sg13g2_xor2_1 _244_ (
    .A(\dpath.a_reg.out [0]),
    .B(\dpath.b_reg.out [0]),
    .X(resp_msg[0])
  );
  sg13g2_nand2_1 _245_ (
    .A(\ctrl.state.out [1]),
    .B(_003_),
    .Y(_055_)
  );
  sg13g2_nor2_1 _246_ (
    .A(\ctrl.state.out [2]),
    .B(_055_),
    .Y(resp_val)
  );
  sg13g2_a21oi_1 _247_ (
    .A1(resp_rdy),
    .A2(resp_val),
    .B1(reset),
    .Y(_056_)
  );
  sg13g2_o21ai_1 _248_ (
    .A1(_036_),
    .A2(req_val),
    .B1(_056_),
    .Y(_000_)
  );
  sg13g2_nand2_1 _249_ (
    .A(\ctrl.state.out [1]),
    .B(_056_),
    .Y(_057_)
  );
  sg13g2_nor4_1 _250_ (
    .A(\dpath.b_reg.out [12]),
    .B(\dpath.b_reg.out [11]),
    .C(\dpath.b_reg.out [10]),
    .D(\dpath.b_reg.out [9]),
    .Y(_058_)
  );
  sg13g2_nor4_1 _251_ (
    .A(\dpath.b_reg.out [0]),
    .B(\dpath.b_reg.out [15]),
    .C(\dpath.b_reg.out [14]),
    .D(\dpath.b_reg.out [13]),
    .Y(_059_)
  );
  sg13g2_and2_1 _252_ (
    .A(_058_),
    .B(_059_),
    .X(_060_)
  );
  sg13g2_nor4_1 _253_ (
    .A(\dpath.b_reg.out [4]),
    .B(\dpath.b_reg.out [3]),
    .C(\dpath.b_reg.out [2]),
    .D(\dpath.b_reg.out [1]),
    .Y(_061_)
  );
  sg13g2_nor4_1 _254_ (
    .A(\dpath.b_reg.out [8]),
    .B(\dpath.b_reg.out [7]),
    .C(\dpath.b_reg.out [6]),
    .D(\dpath.b_reg.out [5]),
    .Y(_062_)
  );
  sg13g2_nand3_1 _255_ (
    .A(_060_),
    .B(_061_),
    .C(_062_),
    .Y(_063_)
  );
  sg13g2_nand2b_1 _256_ (
    .A_N(reset),
    .B(\ctrl.state.out [2]),
    .Y(_064_)
  );
  sg13g2_o21ai_1 _257_ (
    .A1(_063_),
    .A2(_064_),
    .B1(_057_),
    .Y(_001_)
  );
  sg13g2_nand2b_1 _258_ (
    .A_N(_064_),
    .B(_063_),
    .Y(_065_)
  );
  sg13g2_nand2_1 _259_ (
    .A(\ctrl.state.out [0]),
    .B(req_val),
    .Y(_066_)
  );
  sg13g2_o21ai_1 _260_ (
    .A1(reset),
    .A2(_066_),
    .B1(_065_),
    .Y(_002_)
  );
  sg13g2_nand2_1 _261_ (
    .A(_037_),
    .B(\dpath.b_reg.out [15]),
    .Y(_067_)
  );
  sg13g2_xor2_1 _262_ (
    .A(\dpath.a_reg.out [15]),
    .B(\dpath.b_reg.out [15]),
    .X(_068_)
  );
  sg13g2_nand2b_1 _263_ (
    .A_N(\dpath.b_reg.out [14]),
    .B(\dpath.a_reg.out [14]),
    .Y(_069_)
  );
  sg13g2_xnor2_1 _264_ (
    .A(\dpath.b_reg.out [14]),
    .B(\dpath.a_reg.out [14]),
    .Y(_070_)
  );
  sg13g2_nor2b_1 _265_ (
    .A(\dpath.a_reg.out [13]),
    .B_N(\dpath.b_reg.out [13]),
    .Y(_071_)
  );
  sg13g2_nor2b_1 _266_ (
    .A(\dpath.b_reg.out [12]),
    .B_N(\dpath.a_reg.out [12]),
    .Y(_072_)
  );
  sg13g2_xor2_1 _267_ (
    .A(\dpath.b_reg.out [12]),
    .B(\dpath.a_reg.out [12]),
    .X(_073_)
  );
  sg13g2_nor2b_1 _268_ (
    .A(\dpath.a_reg.out [11]),
    .B_N(\dpath.b_reg.out [11]),
    .Y(_074_)
  );
  sg13g2_nor2b_1 _269_ (
    .A(\dpath.b_reg.out [11]),
    .B_N(\dpath.a_reg.out [11]),
    .Y(_075_)
  );
  sg13g2_nor2b_1 _270_ (
    .A(\dpath.b_reg.out [10]),
    .B_N(\dpath.a_reg.out [10]),
    .Y(_076_)
  );
  sg13g2_xor2_1 _271_ (
    .A(\dpath.b_reg.out [10]),
    .B(\dpath.a_reg.out [10]),
    .X(_077_)
  );
  sg13g2_nor2b_1 _272_ (
    .A(\dpath.b_reg.out [9]),
    .B_N(\dpath.a_reg.out [9]),
    .Y(_078_)
  );
  sg13g2_nor2b_1 _273_ (
    .A(\dpath.a_reg.out [9]),
    .B_N(\dpath.b_reg.out [9]),
    .Y(_079_)
  );
  sg13g2_nor2b_1 _274_ (
    .A(\dpath.b_reg.out [8]),
    .B_N(\dpath.a_reg.out [8]),
    .Y(_080_)
  );
  sg13g2_xor2_1 _275_ (
    .A(\dpath.b_reg.out [8]),
    .B(\dpath.a_reg.out [8]),
    .X(_081_)
  );
  sg13g2_nor2_1 _276_ (
    .A(_038_),
    .B(\dpath.a_reg.out [7]),
    .Y(_082_)
  );
  sg13g2_nor2b_1 _277_ (
    .A(\dpath.b_reg.out [6]),
    .B_N(\dpath.a_reg.out [6]),
    .Y(_083_)
  );
  sg13g2_xnor2_1 _278_ (
    .A(\dpath.b_reg.out [6]),
    .B(\dpath.a_reg.out [6]),
    .Y(_084_)
  );
  sg13g2_nand2b_1 _279_ (
    .A_N(\dpath.b_reg.out [5]),
    .B(\dpath.a_reg.out [5]),
    .Y(_085_)
  );
  sg13g2_nor2b_1 _280_ (
    .A(\dpath.b_reg.out [4]),
    .B_N(\dpath.a_reg.out [4]),
    .Y(_086_)
  );
  sg13g2_nand2b_1 _281_ (
    .A_N(\dpath.a_reg.out [4]),
    .B(\dpath.b_reg.out [4]),
    .Y(_087_)
  );
  sg13g2_nand2b_1 _282_ (
    .A_N(_086_),
    .B(_087_),
    .Y(_088_)
  );
  sg13g2_nand2b_1 _283_ (
    .A_N(\dpath.b_reg.out [3]),
    .B(\dpath.a_reg.out [3]),
    .Y(_089_)
  );
  sg13g2_nor2b_1 _284_ (
    .A(\dpath.b_reg.out [2]),
    .B_N(\dpath.a_reg.out [2]),
    .Y(_090_)
  );
  sg13g2_nand2b_1 _285_ (
    .A_N(\dpath.a_reg.out [2]),
    .B(\dpath.b_reg.out [2]),
    .Y(_091_)
  );
  sg13g2_nand2b_1 _286_ (
    .A_N(_090_),
    .B(_091_),
    .Y(_092_)
  );
  sg13g2_nand2b_1 _287_ (
    .A_N(\dpath.b_reg.out [1]),
    .B(\dpath.a_reg.out [1]),
    .Y(_093_)
  );
  sg13g2_nor2b_1 _288_ (
    .A(\dpath.a_reg.out [1]),
    .B_N(\dpath.b_reg.out [1]),
    .Y(_094_)
  );
  sg13g2_xnor2_1 _289_ (
    .A(\dpath.b_reg.out [1]),
    .B(\dpath.a_reg.out [1]),
    .Y(_095_)
  );
  sg13g2_o21ai_1 _290_ (
    .A1(_054_),
    .A2(_094_),
    .B1(_093_),
    .Y(_096_)
  );
  sg13g2_a21oi_1 _291_ (
    .A1(_091_),
    .A2(_096_),
    .B1(_090_),
    .Y(_097_)
  );
  sg13g2_nor2b_1 _292_ (
    .A(\dpath.a_reg.out [3]),
    .B_N(\dpath.b_reg.out [3]),
    .Y(_098_)
  );
  sg13g2_xnor2_1 _293_ (
    .A(\dpath.b_reg.out [3]),
    .B(\dpath.a_reg.out [3]),
    .Y(_099_)
  );
  sg13g2_o21ai_1 _294_ (
    .A1(_097_),
    .A2(_098_),
    .B1(_089_),
    .Y(_100_)
  );
  sg13g2_a21oi_1 _295_ (
    .A1(_087_),
    .A2(_100_),
    .B1(_086_),
    .Y(_101_)
  );
  sg13g2_nor2b_1 _296_ (
    .A(\dpath.a_reg.out [5]),
    .B_N(\dpath.b_reg.out [5]),
    .Y(_102_)
  );
  sg13g2_xnor2_1 _297_ (
    .A(\dpath.b_reg.out [5]),
    .B(\dpath.a_reg.out [5]),
    .Y(_103_)
  );
  sg13g2_o21ai_1 _298_ (
    .A1(_101_),
    .A2(_102_),
    .B1(_085_),
    .Y(_104_)
  );
  sg13g2_a21oi_1 _299_ (
    .A1(_084_),
    .A2(_104_),
    .B1(_083_),
    .Y(_105_)
  );
  sg13g2_a221oi_1 _300_ (
    .A1(_038_),
    .A2(\dpath.a_reg.out [7]),
    .B1(_084_),
    .B2(_104_),
    .C1(_083_),
    .Y(_106_)
  );
  sg13g2_nor3_1 _301_ (
    .A(_081_),
    .B(_082_),
    .C(_106_),
    .Y(_107_)
  );
  sg13g2_nor2_1 _302_ (
    .A(_080_),
    .B(_107_),
    .Y(_108_)
  );
  sg13g2_nor3_1 _303_ (
    .A(_078_),
    .B(_080_),
    .C(_107_),
    .Y(_109_)
  );
  sg13g2_nor3_1 _304_ (
    .A(_077_),
    .B(_079_),
    .C(_109_),
    .Y(_110_)
  );
  sg13g2_nor2_1 _305_ (
    .A(_076_),
    .B(_110_),
    .Y(_111_)
  );
  sg13g2_nor3_1 _306_ (
    .A(_075_),
    .B(_076_),
    .C(_110_),
    .Y(_112_)
  );
  sg13g2_nor3_1 _307_ (
    .A(_073_),
    .B(_074_),
    .C(_112_),
    .Y(_113_)
  );
  sg13g2_nor2b_1 _308_ (
    .A(\dpath.b_reg.out [13]),
    .B_N(\dpath.a_reg.out [13]),
    .Y(_114_)
  );
  sg13g2_nor2_1 _309_ (
    .A(_072_),
    .B(_114_),
    .Y(_115_)
  );
  sg13g2_nor4_1 _310_ (
    .A(_071_),
    .B(_073_),
    .C(_074_),
    .D(_112_),
    .Y(_116_)
  );
  sg13g2_nor2_1 _311_ (
    .A(_071_),
    .B(_115_),
    .Y(_117_)
  );
  sg13g2_nor2_1 _312_ (
    .A(_116_),
    .B(_117_),
    .Y(_118_)
  );
  sg13g2_o21ai_1 _313_ (
    .A1(_116_),
    .A2(_117_),
    .B1(_070_),
    .Y(_119_)
  );
  sg13g2_nand3_1 _314_ (
    .A(_068_),
    .B(_069_),
    .C(_119_),
    .Y(_120_)
  );
  sg13g2_a21o_1 _315_ (
    .A1(_069_),
    .A2(_119_),
    .B1(_068_),
    .X(_121_)
  );
  sg13g2_and2_1 _316_ (
    .A(_120_),
    .B(_121_),
    .X(resp_msg[15])
  );
  sg13g2_xnor2_1 _317_ (
    .A(_054_),
    .B(_095_),
    .Y(resp_msg[1])
  );
  sg13g2_xnor2_1 _318_ (
    .A(_092_),
    .B(_096_),
    .Y(resp_msg[2])
  );
  sg13g2_xnor2_1 _319_ (
    .A(_097_),
    .B(_099_),
    .Y(resp_msg[3])
  );
  sg13g2_xnor2_1 _320_ (
    .A(_088_),
    .B(_100_),
    .Y(resp_msg[4])
  );
  sg13g2_xnor2_1 _321_ (
    .A(_101_),
    .B(_103_),
    .Y(resp_msg[5])
  );
  sg13g2_xor2_1 _322_ (
    .A(_084_),
    .B(_104_),
    .X(resp_msg[6])
  );
  sg13g2_xnor2_1 _323_ (
    .A(\dpath.b_reg.out [7]),
    .B(\dpath.a_reg.out [7]),
    .Y(_122_)
  );
  sg13g2_xnor2_1 _324_ (
    .A(_105_),
    .B(_122_),
    .Y(resp_msg[7])
  );
  sg13g2_o21ai_1 _325_ (
    .A1(_082_),
    .A2(_106_),
    .B1(_081_),
    .Y(_123_)
  );
  sg13g2_nor2b_1 _326_ (
    .A(_107_),
    .B_N(_123_),
    .Y(resp_msg[8])
  );
  sg13g2_nor2_1 _327_ (
    .A(_078_),
    .B(_079_),
    .Y(_124_)
  );
  sg13g2_xnor2_1 _328_ (
    .A(_108_),
    .B(_124_),
    .Y(resp_msg[9])
  );
  sg13g2_o21ai_1 _329_ (
    .A1(_079_),
    .A2(_109_),
    .B1(_077_),
    .Y(_125_)
  );
  sg13g2_nor2b_1 _330_ (
    .A(_110_),
    .B_N(_125_),
    .Y(resp_msg[10])
  );
  sg13g2_nor2_1 _331_ (
    .A(_074_),
    .B(_075_),
    .Y(_126_)
  );
  sg13g2_xnor2_1 _332_ (
    .A(_111_),
    .B(_126_),
    .Y(resp_msg[11])
  );
  sg13g2_o21ai_1 _333_ (
    .A1(_074_),
    .A2(_112_),
    .B1(_073_),
    .Y(_127_)
  );
  sg13g2_nor2b_1 _334_ (
    .A(_113_),
    .B_N(_127_),
    .Y(resp_msg[12])
  );
  sg13g2_nor2_1 _335_ (
    .A(_071_),
    .B(_114_),
    .Y(_128_)
  );
  sg13g2_nor2_1 _336_ (
    .A(_072_),
    .B(_113_),
    .Y(_129_)
  );
  sg13g2_xnor2_1 _337_ (
    .A(_128_),
    .B(_129_),
    .Y(resp_msg[13])
  );
  sg13g2_xnor2_1 _338_ (
    .A(_070_),
    .B(_118_),
    .Y(resp_msg[14])
  );
  sg13g2_nor2b_1 _339_ (
    .A(_068_),
    .B_N(_070_),
    .Y(_130_)
  );
  sg13g2_nand3_1 _340_ (
    .A(_113_),
    .B(_128_),
    .C(_130_),
    .Y(_131_)
  );
  sg13g2_o21ai_1 _341_ (
    .A1(_037_),
    .A2(\dpath.b_reg.out [15]),
    .B1(_069_),
    .Y(_132_)
  );
  sg13g2_a22oi_1 _342_ (
    .A1(_117_),
    .A2(_130_),
    .B1(_132_),
    .B2(_067_),
    .Y(_133_)
  );
  sg13g2_nand3_1 _343_ (
    .A(\ctrl.state.out [2]),
    .B(_131_),
    .C(_133_),
    .Y(_134_)
  );
  sg13g2_nand2_1 _344_ (
    .A(_003_),
    .B(_134_),
    .Y(_135_)
  );
  sg13g2_mux2_1 _345_ (
    .A0(\dpath.a_reg.out [0]),
    .A1(req_msg[0]),
    .S(\ctrl.state.out [0]),
    .X(_136_)
  );
  sg13g2_mux2_1 _346_ (
    .A0(\dpath.b_reg.out [0]),
    .A1(_136_),
    .S(_135_),
    .X(_004_)
  );
  sg13g2_mux2_1 _347_ (
    .A0(\dpath.a_reg.out [1]),
    .A1(req_msg[1]),
    .S(\ctrl.state.out [0]),
    .X(_137_)
  );
  sg13g2_mux2_1 _348_ (
    .A0(\dpath.b_reg.out [1]),
    .A1(_137_),
    .S(_135_),
    .X(_005_)
  );
  sg13g2_mux2_1 _349_ (
    .A0(\dpath.a_reg.out [2]),
    .A1(req_msg[2]),
    .S(\ctrl.state.out [0]),
    .X(_138_)
  );
  sg13g2_mux2_1 _350_ (
    .A0(\dpath.b_reg.out [2]),
    .A1(_138_),
    .S(_135_),
    .X(_006_)
  );
  sg13g2_mux2_1 _351_ (
    .A0(\dpath.a_reg.out [3]),
    .A1(req_msg[3]),
    .S(\ctrl.state.out [0]),
    .X(_139_)
  );
  sg13g2_mux2_1 _352_ (
    .A0(\dpath.b_reg.out [3]),
    .A1(_139_),
    .S(_135_),
    .X(_007_)
  );
  sg13g2_mux2_1 _353_ (
    .A0(\dpath.a_reg.out [4]),
    .A1(req_msg[4]),
    .S(\ctrl.state.out [0]),
    .X(_140_)
  );
  sg13g2_mux2_1 _354_ (
    .A0(\dpath.b_reg.out [4]),
    .A1(_140_),
    .S(_135_),
    .X(_008_)
  );
  sg13g2_mux2_1 _355_ (
    .A0(\dpath.a_reg.out [5]),
    .A1(req_msg[5]),
    .S(\ctrl.state.out [0]),
    .X(_141_)
  );
  sg13g2_mux2_1 _356_ (
    .A0(\dpath.b_reg.out [5]),
    .A1(_141_),
    .S(_135_),
    .X(_009_)
  );
  sg13g2_mux2_1 _357_ (
    .A0(\dpath.a_reg.out [6]),
    .A1(req_msg[6]),
    .S(\ctrl.state.out [0]),
    .X(_142_)
  );
  sg13g2_mux2_1 _358_ (
    .A0(\dpath.b_reg.out [6]),
    .A1(_142_),
    .S(_135_),
    .X(_010_)
  );
  sg13g2_mux2_1 _359_ (
    .A0(\dpath.a_reg.out [7]),
    .A1(req_msg[7]),
    .S(\ctrl.state.out [0]),
    .X(_143_)
  );
  sg13g2_mux2_1 _360_ (
    .A0(\dpath.b_reg.out [7]),
    .A1(_143_),
    .S(_135_),
    .X(_011_)
  );
  sg13g2_mux2_1 _361_ (
    .A0(\dpath.a_reg.out [8]),
    .A1(req_msg[8]),
    .S(\ctrl.state.out [0]),
    .X(_144_)
  );
  sg13g2_mux2_1 _362_ (
    .A0(\dpath.b_reg.out [8]),
    .A1(_144_),
    .S(_135_),
    .X(_012_)
  );
  sg13g2_mux2_1 _363_ (
    .A0(\dpath.a_reg.out [9]),
    .A1(req_msg[9]),
    .S(\ctrl.state.out [0]),
    .X(_145_)
  );
  sg13g2_mux2_1 _364_ (
    .A0(\dpath.b_reg.out [9]),
    .A1(_145_),
    .S(_135_),
    .X(_013_)
  );
  sg13g2_mux2_1 _365_ (
    .A0(\dpath.a_reg.out [10]),
    .A1(req_msg[10]),
    .S(\ctrl.state.out [0]),
    .X(_146_)
  );
  sg13g2_mux2_1 _366_ (
    .A0(\dpath.b_reg.out [10]),
    .A1(_146_),
    .S(_135_),
    .X(_014_)
  );
  sg13g2_mux2_1 _367_ (
    .A0(\dpath.a_reg.out [11]),
    .A1(req_msg[11]),
    .S(\ctrl.state.out [0]),
    .X(_147_)
  );
  sg13g2_mux2_1 _368_ (
    .A0(\dpath.b_reg.out [11]),
    .A1(_147_),
    .S(_135_),
    .X(_015_)
  );
  sg13g2_mux2_1 _369_ (
    .A0(\dpath.a_reg.out [12]),
    .A1(req_msg[12]),
    .S(\ctrl.state.out [0]),
    .X(_148_)
  );
  sg13g2_mux2_1 _370_ (
    .A0(\dpath.b_reg.out [12]),
    .A1(_148_),
    .S(_135_),
    .X(_016_)
  );
  sg13g2_mux2_1 _371_ (
    .A0(\dpath.a_reg.out [13]),
    .A1(req_msg[13]),
    .S(\ctrl.state.out [0]),
    .X(_149_)
  );
  sg13g2_mux2_1 _372_ (
    .A0(\dpath.b_reg.out [13]),
    .A1(_149_),
    .S(_135_),
    .X(_017_)
  );
  sg13g2_mux2_1 _373_ (
    .A0(\dpath.a_reg.out [14]),
    .A1(req_msg[14]),
    .S(\ctrl.state.out [0]),
    .X(_150_)
  );
  sg13g2_mux2_1 _374_ (
    .A0(\dpath.b_reg.out [14]),
    .A1(_150_),
    .S(_135_),
    .X(_018_)
  );
  sg13g2_nand2_1 _375_ (
    .A(_036_),
    .B(_037_),
    .Y(_151_)
  );
  sg13g2_mux2_1 _376_ (
    .A0(\dpath.a_reg.out [15]),
    .A1(req_msg[15]),
    .S(\ctrl.state.out [0]),
    .X(_152_)
  );
  sg13g2_mux2_1 _377_ (
    .A0(\dpath.b_reg.out [15]),
    .A1(_152_),
    .S(_135_),
    .X(_019_)
  );
  sg13g2_and4_1 _378_ (
    .A(\ctrl.state.out [2]),
    .B(_003_),
    .C(_131_),
    .D(_133_),
    .X(_153_)
  );
  sg13g2_nor2b_1 _379_ (
    .A(\ctrl.state.out [0]),
    .B_N(\ctrl.state.out [2]),
    .Y(_154_)
  );
  sg13g2_nand2_1 _380_ (
    .A(_036_),
    .B(\ctrl.state.out [2]),
    .Y(_155_)
  );
  sg13g2_nand2_1 _381_ (
    .A(\ctrl.state.out [2]),
    .B(_003_),
    .Y(_156_)
  );
  sg13g2_a21oi_1 _382_ (
    .A1(_131_),
    .A2(_133_),
    .B1(_156_),
    .Y(_157_)
  );
  sg13g2_a22oi_1 _383_ (
    .A1(\dpath.b_reg.out [0]),
    .A2(_153_),
    .B1(_157_),
    .B2(resp_msg[0]),
    .Y(_158_)
  );
  sg13g2_nor3_1 _384_ (
    .A(\dpath.a_reg.out [0]),
    .B(\ctrl.state.out [0]),
    .C(\ctrl.state.out [2]),
    .Y(_159_)
  );
  sg13g2_a221oi_1 _385_ (
    .A1(\ctrl.state.out [0]),
    .A2(_039_),
    .B1(_154_),
    .B2(_158_),
    .C1(_159_),
    .Y(_020_)
  );
  sg13g2_a22oi_1 _386_ (
    .A1(\dpath.b_reg.out [1]),
    .A2(_153_),
    .B1(_157_),
    .B2(resp_msg[1]),
    .Y(_160_)
  );
  sg13g2_nor3_1 _387_ (
    .A(\ctrl.state.out [0]),
    .B(\ctrl.state.out [2]),
    .C(\dpath.a_reg.out [1]),
    .Y(_161_)
  );
  sg13g2_a221oi_1 _388_ (
    .A1(\ctrl.state.out [0]),
    .A2(_040_),
    .B1(_154_),
    .B2(_160_),
    .C1(_161_),
    .Y(_021_)
  );
  sg13g2_a22oi_1 _389_ (
    .A1(\dpath.b_reg.out [2]),
    .A2(_153_),
    .B1(_157_),
    .B2(resp_msg[2]),
    .Y(_162_)
  );
  sg13g2_nor3_1 _390_ (
    .A(\ctrl.state.out [0]),
    .B(\ctrl.state.out [2]),
    .C(\dpath.a_reg.out [2]),
    .Y(_163_)
  );
  sg13g2_a221oi_1 _391_ (
    .A1(\ctrl.state.out [0]),
    .A2(_041_),
    .B1(_154_),
    .B2(_162_),
    .C1(_163_),
    .Y(_022_)
  );
  sg13g2_a22oi_1 _392_ (
    .A1(\dpath.b_reg.out [3]),
    .A2(_153_),
    .B1(_157_),
    .B2(resp_msg[3]),
    .Y(_164_)
  );
  sg13g2_nor3_1 _393_ (
    .A(\ctrl.state.out [0]),
    .B(\ctrl.state.out [2]),
    .C(\dpath.a_reg.out [3]),
    .Y(_165_)
  );
  sg13g2_a221oi_1 _394_ (
    .A1(\ctrl.state.out [0]),
    .A2(_042_),
    .B1(_154_),
    .B2(_164_),
    .C1(_165_),
    .Y(_023_)
  );
  sg13g2_a22oi_1 _395_ (
    .A1(\dpath.b_reg.out [4]),
    .A2(_153_),
    .B1(_157_),
    .B2(resp_msg[4]),
    .Y(_166_)
  );
  sg13g2_nor3_1 _396_ (
    .A(\ctrl.state.out [0]),
    .B(\ctrl.state.out [2]),
    .C(\dpath.a_reg.out [4]),
    .Y(_167_)
  );
  sg13g2_a221oi_1 _397_ (
    .A1(\ctrl.state.out [0]),
    .A2(_043_),
    .B1(_154_),
    .B2(_166_),
    .C1(_167_),
    .Y(_024_)
  );
  sg13g2_a22oi_1 _398_ (
    .A1(\dpath.b_reg.out [5]),
    .A2(_153_),
    .B1(_157_),
    .B2(resp_msg[5]),
    .Y(_168_)
  );
  sg13g2_nor3_1 _399_ (
    .A(\ctrl.state.out [0]),
    .B(\ctrl.state.out [2]),
    .C(\dpath.a_reg.out [5]),
    .Y(_169_)
  );
  sg13g2_a221oi_1 _400_ (
    .A1(\ctrl.state.out [0]),
    .A2(_044_),
    .B1(_154_),
    .B2(_168_),
    .C1(_169_),
    .Y(_025_)
  );
  sg13g2_a22oi_1 _401_ (
    .A1(\dpath.b_reg.out [6]),
    .A2(_153_),
    .B1(_157_),
    .B2(resp_msg[6]),
    .Y(_170_)
  );
  sg13g2_nor3_1 _402_ (
    .A(\ctrl.state.out [0]),
    .B(\ctrl.state.out [2]),
    .C(\dpath.a_reg.out [6]),
    .Y(_171_)
  );
  sg13g2_a221oi_1 _403_ (
    .A1(\ctrl.state.out [0]),
    .A2(_045_),
    .B1(_154_),
    .B2(_170_),
    .C1(_171_),
    .Y(_026_)
  );
  sg13g2_a22oi_1 _404_ (
    .A1(\dpath.b_reg.out [7]),
    .A2(_153_),
    .B1(_157_),
    .B2(resp_msg[7]),
    .Y(_172_)
  );
  sg13g2_nor3_1 _405_ (
    .A(\ctrl.state.out [0]),
    .B(\ctrl.state.out [2]),
    .C(\dpath.a_reg.out [7]),
    .Y(_173_)
  );
  sg13g2_a221oi_1 _406_ (
    .A1(\ctrl.state.out [0]),
    .A2(_046_),
    .B1(_154_),
    .B2(_172_),
    .C1(_173_),
    .Y(_027_)
  );
  sg13g2_a22oi_1 _407_ (
    .A1(\dpath.b_reg.out [8]),
    .A2(_153_),
    .B1(_157_),
    .B2(resp_msg[8]),
    .Y(_174_)
  );
  sg13g2_nor3_1 _408_ (
    .A(\ctrl.state.out [0]),
    .B(\ctrl.state.out [2]),
    .C(\dpath.a_reg.out [8]),
    .Y(_175_)
  );
  sg13g2_a221oi_1 _409_ (
    .A1(\ctrl.state.out [0]),
    .A2(_047_),
    .B1(_154_),
    .B2(_174_),
    .C1(_175_),
    .Y(_028_)
  );
  sg13g2_a22oi_1 _410_ (
    .A1(\dpath.b_reg.out [9]),
    .A2(_153_),
    .B1(_157_),
    .B2(resp_msg[9]),
    .Y(_176_)
  );
  sg13g2_nor3_1 _411_ (
    .A(\ctrl.state.out [0]),
    .B(\ctrl.state.out [2]),
    .C(\dpath.a_reg.out [9]),
    .Y(_177_)
  );
  sg13g2_a221oi_1 _412_ (
    .A1(\ctrl.state.out [0]),
    .A2(_048_),
    .B1(_154_),
    .B2(_176_),
    .C1(_177_),
    .Y(_029_)
  );
  sg13g2_a22oi_1 _413_ (
    .A1(\dpath.b_reg.out [10]),
    .A2(_153_),
    .B1(_157_),
    .B2(resp_msg[10]),
    .Y(_178_)
  );
  sg13g2_nor3_1 _414_ (
    .A(\ctrl.state.out [0]),
    .B(\ctrl.state.out [2]),
    .C(\dpath.a_reg.out [10]),
    .Y(_179_)
  );
  sg13g2_a221oi_1 _415_ (
    .A1(\ctrl.state.out [0]),
    .A2(_049_),
    .B1(_154_),
    .B2(_178_),
    .C1(_179_),
    .Y(_030_)
  );
  sg13g2_a22oi_1 _416_ (
    .A1(\dpath.b_reg.out [11]),
    .A2(_153_),
    .B1(_157_),
    .B2(resp_msg[11]),
    .Y(_180_)
  );
  sg13g2_nor3_1 _417_ (
    .A(\ctrl.state.out [0]),
    .B(\ctrl.state.out [2]),
    .C(\dpath.a_reg.out [11]),
    .Y(_181_)
  );
  sg13g2_a221oi_1 _418_ (
    .A1(\ctrl.state.out [0]),
    .A2(_050_),
    .B1(_154_),
    .B2(_180_),
    .C1(_181_),
    .Y(_031_)
  );
  sg13g2_a22oi_1 _419_ (
    .A1(\dpath.b_reg.out [12]),
    .A2(_153_),
    .B1(_157_),
    .B2(resp_msg[12]),
    .Y(_182_)
  );
  sg13g2_nor3_1 _420_ (
    .A(\ctrl.state.out [0]),
    .B(\ctrl.state.out [2]),
    .C(\dpath.a_reg.out [12]),
    .Y(_183_)
  );
  sg13g2_a221oi_1 _421_ (
    .A1(\ctrl.state.out [0]),
    .A2(_051_),
    .B1(_154_),
    .B2(_182_),
    .C1(_183_),
    .Y(_032_)
  );
  sg13g2_a22oi_1 _422_ (
    .A1(\dpath.b_reg.out [13]),
    .A2(_153_),
    .B1(_157_),
    .B2(resp_msg[13]),
    .Y(_184_)
  );
  sg13g2_nor3_1 _423_ (
    .A(\ctrl.state.out [0]),
    .B(\ctrl.state.out [2]),
    .C(\dpath.a_reg.out [13]),
    .Y(_185_)
  );
  sg13g2_a221oi_1 _424_ (
    .A1(\ctrl.state.out [0]),
    .A2(_052_),
    .B1(_154_),
    .B2(_184_),
    .C1(_185_),
    .Y(_033_)
  );
  sg13g2_a22oi_1 _425_ (
    .A1(\dpath.b_reg.out [14]),
    .A2(_153_),
    .B1(_157_),
    .B2(resp_msg[14]),
    .Y(_186_)
  );
  sg13g2_nor3_1 _426_ (
    .A(\ctrl.state.out [0]),
    .B(\ctrl.state.out [2]),
    .C(\dpath.a_reg.out [14]),
    .Y(_187_)
  );
  sg13g2_a221oi_1 _427_ (
    .A1(\ctrl.state.out [0]),
    .A2(_053_),
    .B1(_154_),
    .B2(_186_),
    .C1(_187_),
    .Y(_034_)
  );
  sg13g2_nand3_1 _428_ (
    .A(_120_),
    .B(_121_),
    .C(_157_),
    .Y(_188_)
  );
  sg13g2_a21oi_1 _429_ (
    .A1(\dpath.b_reg.out [15]),
    .A2(_153_),
    .B1(_155_),
    .Y(_189_)
  );
  sg13g2_o21ai_1 _430_ (
    .A1(_036_),
    .A2(req_msg[31]),
    .B1(_151_),
    .Y(_190_)
  );
  sg13g2_a22oi_1 _431_ (
    .A1(_188_),
    .A2(_189_),
    .B1(_190_),
    .B2(_155_),
    .Y(_035_)
  );
  (* src = "gcd.v:570.3-576.6" *)
  sg13g2_dfrbp_1 _432_ (
    .CLK(clk),
    .D(_004_),
    .Q(\dpath.b_reg.out [0]),
    .Q_N(_222_),
    .RESET_B(1'h1)
  );
  (* src = "gcd.v:570.3-576.6" *)
  sg13g2_dfrbp_1 _433_ (
    .CLK(clk),
    .D(_005_),
    .Q(\dpath.b_reg.out [1]),
    .Q_N(_221_),
    .RESET_B(1'h1)
  );
  (* src = "gcd.v:570.3-576.6" *)
  sg13g2_dfrbp_1 _434_ (
    .CLK(clk),
    .D(_006_),
    .Q(\dpath.b_reg.out [2]),
    .Q_N(_220_),
    .RESET_B(1'h1)
  );
  (* src = "gcd.v:570.3-576.6" *)
  sg13g2_dfrbp_1 _435_ (
    .CLK(clk),
    .D(_007_),
    .Q(\dpath.b_reg.out [3]),
    .Q_N(_219_),
    .RESET_B(1'h1)
  );
  (* src = "gcd.v:570.3-576.6" *)
  sg13g2_dfrbp_1 _436_ (
    .CLK(clk),
    .D(_008_),
    .Q(\dpath.b_reg.out [4]),
    .Q_N(_218_),
    .RESET_B(1'h1)
  );
  (* src = "gcd.v:570.3-576.6" *)
  sg13g2_dfrbp_1 _437_ (
    .CLK(clk),
    .D(_009_),
    .Q(\dpath.b_reg.out [5]),
    .Q_N(_217_),
    .RESET_B(1'h1)
  );
  (* src = "gcd.v:570.3-576.6" *)
  sg13g2_dfrbp_1 _438_ (
    .CLK(clk),
    .D(_010_),
    .Q(\dpath.b_reg.out [6]),
    .Q_N(_216_),
    .RESET_B(1'h1)
  );
  (* src = "gcd.v:570.3-576.6" *)
  sg13g2_dfrbp_1 _439_ (
    .CLK(clk),
    .D(_011_),
    .Q(\dpath.b_reg.out [7]),
    .Q_N(_215_),
    .RESET_B(1'h1)
  );
  (* src = "gcd.v:570.3-576.6" *)
  sg13g2_dfrbp_1 _440_ (
    .CLK(clk),
    .D(_012_),
    .Q(\dpath.b_reg.out [8]),
    .Q_N(_214_),
    .RESET_B(1'h1)
  );
  (* src = "gcd.v:570.3-576.6" *)
  sg13g2_dfrbp_1 _441_ (
    .CLK(clk),
    .D(_013_),
    .Q(\dpath.b_reg.out [9]),
    .Q_N(_213_),
    .RESET_B(1'h1)
  );
  (* src = "gcd.v:570.3-576.6" *)
  sg13g2_dfrbp_1 _442_ (
    .CLK(clk),
    .D(_014_),
    .Q(\dpath.b_reg.out [10]),
    .Q_N(_212_),
    .RESET_B(1'h1)
  );
  (* src = "gcd.v:570.3-576.6" *)
  sg13g2_dfrbp_1 _443_ (
    .CLK(clk),
    .D(_015_),
    .Q(\dpath.b_reg.out [11]),
    .Q_N(_211_),
    .RESET_B(1'h1)
  );
  (* src = "gcd.v:570.3-576.6" *)
  sg13g2_dfrbp_1 _444_ (
    .CLK(clk),
    .D(_016_),
    .Q(\dpath.b_reg.out [12]),
    .Q_N(_210_),
    .RESET_B(1'h1)
  );
  (* src = "gcd.v:570.3-576.6" *)
  sg13g2_dfrbp_1 _445_ (
    .CLK(clk),
    .D(_017_),
    .Q(\dpath.b_reg.out [13]),
    .Q_N(_209_),
    .RESET_B(1'h1)
  );
  (* src = "gcd.v:570.3-576.6" *)
  sg13g2_dfrbp_1 _446_ (
    .CLK(clk),
    .D(_018_),
    .Q(\dpath.b_reg.out [14]),
    .Q_N(_208_),
    .RESET_B(1'h1)
  );
  (* src = "gcd.v:570.3-576.6" *)
  sg13g2_dfrbp_1 _447_ (
    .CLK(clk),
    .D(_019_),
    .Q(\dpath.b_reg.out [15]),
    .Q_N(_223_),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbp_1 _448_ (
    .CLK(clk),
    .D(_000_),
    .Q(\ctrl.state.out [0]),
    .Q_N(_003_),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbp_1 _449_ (
    .CLK(clk),
    .D(_001_),
    .Q(\ctrl.state.out [1]),
    .Q_N(_224_),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbp_1 _450_ (
    .CLK(clk),
    .D(_002_),
    .Q(\ctrl.state.out [2]),
    .Q_N(_207_),
    .RESET_B(1'h1)
  );
  (* src = "gcd.v:570.3-576.6" *)
  sg13g2_dfrbp_1 _451_ (
    .CLK(clk),
    .D(_020_),
    .Q(\dpath.a_reg.out [0]),
    .Q_N(_206_),
    .RESET_B(1'h1)
  );
  (* src = "gcd.v:570.3-576.6" *)
  sg13g2_dfrbp_1 _452_ (
    .CLK(clk),
    .D(_021_),
    .Q(\dpath.a_reg.out [1]),
    .Q_N(_205_),
    .RESET_B(1'h1)
  );
  (* src = "gcd.v:570.3-576.6" *)
  sg13g2_dfrbp_1 _453_ (
    .CLK(clk),
    .D(_022_),
    .Q(\dpath.a_reg.out [2]),
    .Q_N(_204_),
    .RESET_B(1'h1)
  );
  (* src = "gcd.v:570.3-576.6" *)
  sg13g2_dfrbp_1 _454_ (
    .CLK(clk),
    .D(_023_),
    .Q(\dpath.a_reg.out [3]),
    .Q_N(_203_),
    .RESET_B(1'h1)
  );
  (* src = "gcd.v:570.3-576.6" *)
  sg13g2_dfrbp_1 _455_ (
    .CLK(clk),
    .D(_024_),
    .Q(\dpath.a_reg.out [4]),
    .Q_N(_202_),
    .RESET_B(1'h1)
  );
  (* src = "gcd.v:570.3-576.6" *)
  sg13g2_dfrbp_1 _456_ (
    .CLK(clk),
    .D(_025_),
    .Q(\dpath.a_reg.out [5]),
    .Q_N(_201_),
    .RESET_B(1'h1)
  );
  (* src = "gcd.v:570.3-576.6" *)
  sg13g2_dfrbp_1 _457_ (
    .CLK(clk),
    .D(_026_),
    .Q(\dpath.a_reg.out [6]),
    .Q_N(_200_),
    .RESET_B(1'h1)
  );
  (* src = "gcd.v:570.3-576.6" *)
  sg13g2_dfrbp_1 _458_ (
    .CLK(clk),
    .D(_027_),
    .Q(\dpath.a_reg.out [7]),
    .Q_N(_199_),
    .RESET_B(1'h1)
  );
  (* src = "gcd.v:570.3-576.6" *)
  sg13g2_dfrbp_1 _459_ (
    .CLK(clk),
    .D(_028_),
    .Q(\dpath.a_reg.out [8]),
    .Q_N(_198_),
    .RESET_B(1'h1)
  );
  (* src = "gcd.v:570.3-576.6" *)
  sg13g2_dfrbp_1 _460_ (
    .CLK(clk),
    .D(_029_),
    .Q(\dpath.a_reg.out [9]),
    .Q_N(_197_),
    .RESET_B(1'h1)
  );
  (* src = "gcd.v:570.3-576.6" *)
  sg13g2_dfrbp_1 _461_ (
    .CLK(clk),
    .D(_030_),
    .Q(\dpath.a_reg.out [10]),
    .Q_N(_196_),
    .RESET_B(1'h1)
  );
  (* src = "gcd.v:570.3-576.6" *)
  sg13g2_dfrbp_1 _462_ (
    .CLK(clk),
    .D(_031_),
    .Q(\dpath.a_reg.out [11]),
    .Q_N(_195_),
    .RESET_B(1'h1)
  );
  (* src = "gcd.v:570.3-576.6" *)
  sg13g2_dfrbp_1 _463_ (
    .CLK(clk),
    .D(_032_),
    .Q(\dpath.a_reg.out [12]),
    .Q_N(_194_),
    .RESET_B(1'h1)
  );
  (* src = "gcd.v:570.3-576.6" *)
  sg13g2_dfrbp_1 _464_ (
    .CLK(clk),
    .D(_033_),
    .Q(\dpath.a_reg.out [13]),
    .Q_N(_193_),
    .RESET_B(1'h1)
  );
  (* src = "gcd.v:570.3-576.6" *)
  sg13g2_dfrbp_1 _465_ (
    .CLK(clk),
    .D(_034_),
    .Q(\dpath.a_reg.out [14]),
    .Q_N(_192_),
    .RESET_B(1'h1)
  );
  (* src = "gcd.v:570.3-576.6" *)
  sg13g2_dfrbp_1 _466_ (
    .CLK(clk),
    .D(_035_),
    .Q(\dpath.a_reg.out [15]),
    .Q_N(_191_),
    .RESET_B(1'h1)
  );
  assign \ctrl$b_mux_sel  = \ctrl.state.out [0];
  assign \ctrl$clk  = clk;
  assign \ctrl$req_rdy  = \ctrl.state.out [0];
  assign \ctrl$req_val  = req_val;
  assign \ctrl$reset  = reset;
  assign \ctrl$resp_rdy  = resp_rdy;
  assign \ctrl$resp_val  = resp_val;
  assign \ctrl.b_mux_sel  = \ctrl.state.out [0];
  assign \ctrl.clk  = clk;
  assign \ctrl.req_rdy  = \ctrl.state.out [0];
  assign \ctrl.req_val  = req_val;
  assign \ctrl.reset  = reset;
  assign \ctrl.resp_rdy  = resp_rdy;
  assign \ctrl.resp_val  = resp_val;
  assign \ctrl.state$clk  = clk;
  assign \ctrl.state$reset  = reset;
  assign \ctrl.state.clk  = clk;
  assign \ctrl.state.reset  = reset;
  assign \dpath$b_mux_sel  = \ctrl.state.out [0];
  assign \dpath$clk  = clk;
  assign \dpath$req_msg_a  = req_msg[31:16];
  assign \dpath$req_msg_b  = req_msg[15:0];
  assign \dpath$reset  = reset;
  assign \dpath$resp_msg  = resp_msg;
  assign \dpath.a_lt_b$clk  = clk;
  assign \dpath.a_lt_b$in0  = \dpath.a_reg.out ;
  assign \dpath.a_lt_b$in1  = \dpath.b_reg.out ;
  assign \dpath.a_lt_b$reset  = reset;
  assign \dpath.a_lt_b.clk  = clk;
  assign \dpath.a_lt_b.in0  = \dpath.a_reg.out ;
  assign \dpath.a_lt_b.in1  = \dpath.b_reg.out ;
  assign \dpath.a_lt_b.reset  = reset;
  assign \dpath.a_mux$clk  = clk;
  assign \dpath.a_mux$in_$000  = req_msg[31:16];
  assign \dpath.a_mux$in_$001  = resp_msg;
  assign \dpath.a_mux$in_$002  = \dpath.b_reg.out ;
  assign \dpath.a_mux$reset  = reset;
  assign \dpath.a_mux.clk  = clk;
  assign \dpath.a_mux.in_$000  = req_msg[31:16];
  assign \dpath.a_mux.in_$001  = resp_msg;
  assign \dpath.a_mux.in_$002  = \dpath.b_reg.out ;
  assign \dpath.a_mux.in_[0]  = req_msg[31:16];
  assign \dpath.a_mux.in_[1]  = resp_msg;
  assign \dpath.a_mux.in_[2]  = \dpath.b_reg.out ;
  assign \dpath.a_mux.reset  = reset;
  assign \dpath.a_reg$clk  = clk;
  assign \dpath.a_reg$out  = \dpath.a_reg.out ;
  assign \dpath.a_reg$reset  = reset;
  assign \dpath.a_reg.clk  = clk;
  assign \dpath.a_reg.reset  = reset;
  assign \dpath.b_mux$clk  = clk;
  assign \dpath.b_mux$in_$000  = \dpath.a_reg.out ;
  assign \dpath.b_mux$in_$001  = req_msg[15:0];
  assign \dpath.b_mux$reset  = reset;
  assign \dpath.b_mux$sel  = \ctrl.state.out [0];
  assign \dpath.b_mux.clk  = clk;
  assign \dpath.b_mux.in_$000  = \dpath.a_reg.out ;
  assign \dpath.b_mux.in_$001  = req_msg[15:0];
  assign \dpath.b_mux.in_[0]  = \dpath.a_reg.out ;
  assign \dpath.b_mux.in_[1]  = req_msg[15:0];
  assign \dpath.b_mux.reset  = reset;
  assign \dpath.b_mux.sel  = \ctrl.state.out [0];
  assign \dpath.b_mux_sel  = \ctrl.state.out [0];
  assign \dpath.b_reg$clk  = clk;
  assign \dpath.b_reg$out  = \dpath.b_reg.out ;
  assign \dpath.b_reg$reset  = reset;
  assign \dpath.b_reg.clk  = clk;
  assign \dpath.b_reg.reset  = reset;
  assign \dpath.b_reg_out  = \dpath.b_reg.out ;
  assign \dpath.b_zero$clk  = clk;
  assign \dpath.b_zero$in_  = \dpath.b_reg.out ;
  assign \dpath.b_zero$reset  = reset;
  assign \dpath.b_zero.clk  = clk;
  assign \dpath.b_zero.in_  = \dpath.b_reg.out ;
  assign \dpath.b_zero.reset  = reset;
  assign \dpath.clk  = clk;
  assign \dpath.req_msg_a  = req_msg[31:16];
  assign \dpath.req_msg_b  = req_msg[15:0];
  assign \dpath.reset  = reset;
  assign \dpath.resp_msg  = resp_msg;
  assign \dpath.sub$clk  = clk;
  assign \dpath.sub$in0  = \dpath.a_reg.out ;
  assign \dpath.sub$in1  = \dpath.b_reg.out ;
  assign \dpath.sub$out  = resp_msg;
  assign \dpath.sub$reset  = reset;
  assign \dpath.sub.clk  = clk;
  assign \dpath.sub.in0  = \dpath.a_reg.out ;
  assign \dpath.sub.in1  = \dpath.b_reg.out ;
  assign \dpath.sub.out  = resp_msg;
  assign \dpath.sub.reset  = reset;
  assign \dpath.sub_out  = resp_msg;
  assign req_rdy = \ctrl.state.out [0];
endmodule
